// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Creator, CreatorTableId } from "./tables/Creator.sol";
import { Name, NameTableId } from "./tables/Name.sol";
import { PathKey, PathKeyTableId } from "./tables/PathKey.sol";
import { Path, PathTableId } from "./tables/Path.sol";
import { Minted, MintedTableId } from "./tables/Minted.sol";
import { TemplateIdIncrement, TemplateIdIncrementTableId } from "./tables/TemplateIdIncrement.sol";
import { DerivativeIncrement, DerivativeIncrementTableId } from "./tables/DerivativeIncrement.sol";
