// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { Creator, CreatorTableId } from "./tables/Creator.sol";
import { Name, NameTableId } from "./tables/Name.sol";
import { Media, MediaTableId } from "./tables/Media.sol";
import { PathKey, PathKeyTableId } from "./tables/PathKey.sol";
import { Path, PathTableId } from "./tables/Path.sol";
import { TemplateIncrement, TemplateIncrementTableId } from "./tables/TemplateIncrement.sol";
import { DerivativeIncrement, DerivativeIncrementTableId } from "./tables/DerivativeIncrement.sol";
