// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { GameConfig, GameConfigTableId } from "./tables/GameConfig.sol";
import { Creator, CreatorTableId } from "./tables/Creator.sol";
import { Name, NameTableId } from "./tables/Name.sol";
import { Caption, CaptionTableId } from "./tables/Caption.sol";
import { PathKey, PathKeyTableId } from "./tables/PathKey.sol";
import { Path, PathTableId } from "./tables/Path.sol";
import { Minted, MintedTableId } from "./tables/Minted.sol";
import { TemplateKey, TemplateKeyTableId } from "./tables/TemplateKey.sol";
import { Reserved, ReservedTableId } from "./tables/Reserved.sol";
import { TemplateIdIncrement, TemplateIdIncrementTableId } from "./tables/TemplateIdIncrement.sol";
import { DerivativeIdIncrement, DerivativeIdIncrementTableId } from "./tables/DerivativeIdIncrement.sol";
