// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITemplateSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITemplateSystem {
  function createTemplate(string calldata name) external returns (uint256);

  function drawPath(uint256 templateId, uint128[][] calldata paths) external;

  function mintTemplate(string calldata name, string calldata media) external;

  function templateTokenURI(uint256 tokenId) external view returns (string memory);

  function floatize(uint256 number) external pure returns (string memory);

  function pack(uint128 a, uint128 b) external pure returns (uint256);

  function unpack(uint256 packed) external pure returns (uint128 a, uint128 b);

  function getPackedPaths(uint128[][] calldata paths) external pure returns (uint256[] memory packedPaths);
}
