// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITemplateSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITemplateSystem {
  function createTemplate(string calldata name) external returns (uint256);

  function drawPaths(uint256 templateId, uint128[][] calldata paths) external;

  function mintTemplate(uint256 templateId) external;

  function templateTokenURI(uint256 tokenId) external view returns (string memory);
}
